package vn.edu.eaut.lab5.ui;
import vn.edu.eaut.lab5.bus.KhachHangBUS; import vn.edu.eaut.lab5.model.KhachHang; import vn.edu.eaut.lab5.util.PhoneDocumentFilter;
import javax.swing.*; import javax.swing.table.DefaultTableModel; import javax.swing.text.AbstractDocument; import java.awt.*; import java.util.List;
public class KhachHangPanel extends JPanel {
 private final KhachHangBUS bus=new KhachHangBUS(); private final JTextField id=new JTextField(),name=new JTextField(),phone=new JTextField(),address=new JTextField(),query=new JTextField(); private final JButton add=new JButton("Them"),edit=new JButton("Sua"),del=new JButton("Xoa"),refresh=new JButton("Lam moi"),find=new JButton("Tim kiem"); private final DefaultTableModel model=new DefaultTableModel(new Object[]{"Ma KH","Ho ten","So dien thoai","Dia chi"},0){public boolean isCellEditable(int r,int c){return false;}}; private final JTable table=new JTable(model);
 public KhachHangPanel(){setLayout(new BorderLayout(8,8));setBorder(BorderFactory.createEmptyBorder(10,10,10,10));id.setEditable(false);((AbstractDocument)phone.getDocument()).setDocumentFilter(new PhoneDocumentFilter());JPanel f=new JPanel(new GridLayout(4,2,8,8));f.add(new JLabel("Ma khach hang:"));f.add(id);f.add(new JLabel("Ten khach hang:"));f.add(name);f.add(new JLabel("So dien thoai:"));f.add(phone);f.add(new JLabel("Dia chi:"));f.add(address);JPanel a=new JPanel(new FlowLayout(FlowLayout.LEFT));for(JButton b:new JButton[]{add,edit,del,refresh})a.add(b);JPanel q=new JPanel(new BorderLayout(5,0));q.add(new JLabel("Tim:"),BorderLayout.WEST);q.add(query);q.add(find,BorderLayout.EAST);JPanel top=new JPanel(new BorderLayout(5,5));top.add(f,BorderLayout.NORTH);top.add(a,BorderLayout.CENTER);top.add(q,BorderLayout.SOUTH);add(top,BorderLayout.NORTH);table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);table.setRowHeight(25);add(new JScrollPane(table));add.addActionListener(e->save(true));edit.addActionListener(e->save(false));del.addActionListener(e->delete());refresh.addActionListener(e->{clear();load("");});find.addActionListener(e->load(query.getText()));query.addActionListener(e->load(query.getText()));table.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting())fill();});load("");}
 private void load(String q){setButtonsEnabled(false);new SwingWorker<List<KhachHang>,Void>(){protected List<KhachHang> doInBackground()throws Exception{return q.isBlank()?bus.findAll():bus.search(q);}protected void done(){try{model.setRowCount(0);for(KhachHang x:get())model.addRow(new Object[]{x.getMaKh(),x.getTenKh(),x.getSdt(),x.getDiaChi()});}catch(Exception e){error("Khong the tai khach hang",e);}finally{setButtonsEnabled(true);}}}.execute();}
 private void save(boolean isNew){try{KhachHang x=new KhachHang(isNew?0:Integer.parseInt(id.getText()),name.getText().trim(),phone.getText().trim(),address.getText().trim());if(!isNew&&id.getText().isBlank())throw new IllegalArgumentException("Chon khach hang can sua");if(bus.save(x)){clear();load("");}}catch(Exception e){error("Khong the luu khach hang",e);}}
 private void delete(){try{if(id.getText().isBlank())throw new IllegalArgumentException("Chon khach hang can xoa");if(JOptionPane.showConfirmDialog(this,"Xoa khach hang nay?","Xac nhan",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION&&bus.delete(Integer.parseInt(id.getText()))){clear();load("");}}catch(Exception e){error("Khong the xoa khach hang",e);}}
 private void fill(){int r=table.getSelectedRow();if(r<0)return;id.setText(model.getValueAt(r,0).toString());name.setText(model.getValueAt(r,1).toString());phone.setText(model.getValueAt(r,2).toString());address.setText(String.valueOf(model.getValueAt(r,3)));}private void clear(){id.setText("");name.setText("");phone.setText("");address.setText("");table.clearSelection();}private void setButtonsEnabled(boolean b){for(JButton x:new JButton[]{add,edit,del,refresh,find})x.setEnabled(b);}private void error(String t,Exception e){Throwable x=e.getCause()==null?e:e.getCause();JOptionPane.showMessageDialog(this,t+": "+x.getMessage(),"Loi",JOptionPane.ERROR_MESSAGE);}
}
