# Application Configuration
spring.application.name=lab12-spring-mvc-student
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Encoding & Messages
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.messages.encoding=UTF-8

# Logging
logging.level.vn.edu.eaut.lab12=DEBUG
logging.level.org.springframework.web=INFO
